import 'package:flutter/material.dart';
import '../models/business_models.dart';
import '../services/business_store.dart';

class AdvancedScreen extends StatefulWidget {
  const AdvancedScreen({super.key, required this.store});
  final BusinessStore store;
  @override State<AdvancedScreen> createState() => _AdvancedScreenState();
}

class _AdvancedScreenState extends State<AdvancedScreen> {
  int tab = 0;
  String money(double v) => '${widget.store.prefs.getString('currency') ?? '৳'}${v.toStringAsFixed(2)}';
  String id() => DateTime.now().microsecondsSinceEpoch.toString();

  Future<void> supplierDialog([Supplier? old]) async {
    final name=TextEditingController(text:old?.name??''); final phone=TextEditingController(text:old?.phone??''); final address=TextEditingController(text:old?.address??'');
    await showDialog(context:context,builder:(_)=>AlertDialog(title:Text(old==null?'Add supplier':'Edit supplier'),content:SingleChildScrollView(child:Column(children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Name')),TextField(controller:phone,decoration:const InputDecoration(labelText:'Phone')),TextField(controller:address,decoration:const InputDecoration(labelText:'Address'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:()async{if(name.text.trim().isEmpty)return;final list=widget.store.suppliers;final x=Supplier(id:old?.id??id(),name:name.text.trim(),phone:phone.text.trim(),address:address.text.trim(),due:old?.due??0);if(old==null)list.add(x);else list[list.indexWhere((e)=>e.id==old.id)]=x;await widget.store.saveSuppliers(list);if(mounted)Navigator.pop(context);setState((){});},child:const Text('Save'))]));
    name.dispose();phone.dispose();address.dispose();
  }

  Future<void> paymentDialog() async {
    final amount=TextEditingController(); final note=TextEditingController(); String type='received'; String party='';
    await showDialog(context:context,builder:(_)=>StatefulBuilder(builder:(c,s){final customers=widget.store.customers;final suppliers=widget.store.suppliers;return AlertDialog(title:const Text('Add payment'),content:SingleChildScrollView(child:Column(children:[DropdownButtonFormField<String>(initialValue:type,items:const[DropdownMenuItem(value:'received',child:Text('Received from customer')),DropdownMenuItem(value:'paid',child:Text('Paid to supplier'))],onChanged:(v){if(v!=null)s(()=>type=v);}),const SizedBox(height:8),DropdownButtonFormField<String>(initialValue:party.isEmpty?null:party,items:[if(type=='received')...customers.map((e)=>DropdownMenuItem(value:e.id,child:Text(e.name))),if(type=='paid')...suppliers.map((e)=>DropdownMenuItem(value:e.id,child:Text(e.name)))],onChanged:(v)=>s(()=>party=v??''),decoration:const InputDecoration(labelText:'Party')),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Amount')),TextField(controller:note,decoration:const InputDecoration(labelText:'Note'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()async{final a=double.tryParse(amount.text)??0;if(a<=0||party.isEmpty)return;final p=Payment(id:id(),date:DateTime.now(),partyId:party,amount:a,note:note.text.trim(),type:type);final ps=widget.store.payments..add(p);await widget.store.savePayments(ps);if(type=='received'){final list=widget.store.customers;final i=list.indexWhere((e)=>e.id==party);if(i>=0){list[i].due-=a;await widget.store.saveCustomers(list);}}else{final list=widget.store.suppliers;final i=list.indexWhere((e)=>e.id==party);if(i>=0){list[i].due-=a;await widget.store.saveSuppliers(list);}}if(mounted)Navigator.pop(c);setState((){});},child:const Text('Save'))] }));
    amount.dispose();note.dispose();
  }

  Future<void> stockMoveDialog() async {
    String product=''; String type='in'; final q=TextEditingController(); final note=TextEditingController();
    await showDialog(context:context,builder:(_)=>StatefulBuilder(builder:(c,s)=>AlertDialog(title:const Text('Stock movement'),content:SingleChildScrollView(child:Column(children:[DropdownButtonFormField<String>(initialValue:product.isEmpty?null:product,items:[for(final p in widget.store.products)DropdownMenuItem(value:p.id,child:Text(p.name))],onChanged:(v)=>s(()=>product=v??''),decoration:const InputDecoration(labelText:'Product')),DropdownButtonFormField<String>(initialValue:type,items:const[DropdownMenuItem(value:'in',child:Text('Stock In')),DropdownMenuItem(value:'out',child:Text('Stock Out')),DropdownMenuItem(value:'adjustment',child:Text('Adjustment'))],onChanged:(v){if(v!=null)s(()=>type=v);}),TextField(controller:q,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Quantity')),TextField(controller:note,decoration:const InputDecoration(labelText:'Note'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()async{final n=double.tryParse(q.text)??0;if(product.isEmpty||n<=0)return;final list=widget.store.products;final i=list.indexWhere((e)=>e.id==product);if(i<0)return;final delta=type=='out'?-n:n;list[i].stock=(type=='adjustment'?n:list[i].stock+delta);if(list[i].stock<0)list[i].stock=0;await widget.store.saveProducts(list);await widget.store.saveStockMoves(widget.store.stockMoves..add(StockMove(id:id(),date:DateTime.now(),productId:product,quantity:n,type:type,note:note.text.trim())));if(mounted)Navigator.pop(c);setState((){});},child:const Text('Save'))]));
    q.dispose();note.dispose();
  }

  Future<void> returnDialog() async {
    final sales=widget.store.sales; String sale=''; String product=''; final q=TextEditingController(); final note=TextEditingController();
    await showDialog(context:context,builder:(_)=>StatefulBuilder(builder:(c,s){final selected=sales.where((e)=>e.id==sale).toList();final items=selected.isEmpty?const <SaleItem>[]:selected.first.items;return AlertDialog(title:const Text('Sales return'),content:SingleChildScrollView(child:Column(children:[DropdownButtonFormField<String>(initialValue:sale.isEmpty?null:sale,items:[for(final x in sales)DropdownMenuItem(value:x.id,child:Text('#${x.id.substring(x.id.length-6)} • ${money(x.total)}'))],onChanged:(v){s((){sale=v??'';product='';});},decoration:const InputDecoration(labelText:'Sale')),DropdownButtonFormField<String>(initialValue:product.isEmpty?null:product,items:[for(final x in items)DropdownMenuItem(value:x.productId,child:Text(x.name))],onChanged:(v)=>s(()=>product=v??''),decoration:const InputDecoration(labelText:'Product')),TextField(controller:q,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Quantity')),TextField(controller:note,decoration:const InputDecoration(labelText:'Note'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()async{final n=double.tryParse(q.text)??0;final sl=sales.where((e)=>e.id==sale).toList();final it=sl.isEmpty?const <SaleItem>[]:sl.first.items.where((e)=>e.productId==product).toList();if(sl.isEmpty||it.isEmpty||n<=0||n>it.first.quantity)return;final amount=n*it.first.price;final ps=widget.store.products;final pi=ps.indexWhere((e)=>e.id==product);if(pi>=0){ps[pi].stock+=n;await widget.store.saveProducts(ps);}final rs=widget.store.returns..add(ReturnRecord(id:id(),date:DateTime.now(),saleId:sale,productId:product,quantity:n,amount:amount,note:note.text.trim()));await widget.store.saveReturns(rs);if(mounted)Navigator.pop(c);setState((){});},child:const Text('Save return'))] }));
    q.dispose();note.dispose();
  }

  void receipt(Sale sale) {
    final shop=widget.store.prefs.getString('shop')??'আমার দোকান';final currency=widget.store.prefs.getString('currency')??'৳';
    showDialog(context:context,builder:(_)=>AlertDialog(title:Text('$shop — Invoice ${sale.id.substring(sale.id.length-6)}'),content:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Date: ${sale.date}'),const Divider(),for(final i in sale.items)Padding(padding:const EdgeInsets.symmetric(vertical:3),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Expanded(child:Text('${i.name} × ${i.quantity}')),Text('$currency${i.subtotal.toStringAsFixed(2)}')])),const Divider(),Text('Total: $currency${sale.total.toStringAsFixed(2)}',style:const TextStyle(fontWeight:FontWeight.bold)),Text('Paid: $currency${sale.paid.toStringAsFixed(2)}'),Text('Due: $currency${sale.due.toStringAsFixed(2)}'),])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Close'))]));
  }

  @override Widget build(BuildContext context){final suppliers=widget.store.suppliers;final payments=widget.store.payments;final returns=widget.store.returns;final moves=widget.store.stockMoves;final sales=widget.store.sales;return Scaffold(appBar:AppBar(title:const Text('Business Tools')),body:Column(children:[SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[for(final x in ['Suppliers','Payments','Returns','Stock Moves','Invoices'])Padding(padding:const EdgeInsets.all(4),child:ChoiceChip(label:Text(x),selected:tab==['Suppliers','Payments','Returns','Stock Moves','Invoices'].indexOf(x),onSelected:(_){setState(()=>tab=['Suppliers','Payments','Returns','Stock Moves','Invoices'].indexOf(x));}})])),Expanded(child:ListView(padding:const EdgeInsets.all(12),children:[if(tab==0)...[for(final s in suppliers)Card(child:ListTile(title:Text(s.name),subtitle:Text('${s.phone}\nDue: ${money(s.due)}'),isThreeLine:true,onTap:()=>supplierDialog(s),trailing:IconButton(icon:const Icon(Icons.delete),onPressed:()async{final l=widget.store.suppliers..removeWhere((e)=>e.id==s.id);await widget.store.saveSuppliers(l);setState((){});})),),],if(tab==1)...[for(final p in payments)Card(child:ListTile(title:Text('${p.type=='received'?'Received':'Paid'} ${money(p.amount)}'),subtitle:Text('${p.date}\n${p.note}'),isThreeLine:true)),],if(tab==2)...[for(final r in returns)Card(child:ListTile(title:Text('Return ${money(r.amount)} • Qty ${r.quantity}'),subtitle:Text('Sale ${r.saleId} • Product ${r.productId}'))),],if(tab==3)...[for(final m in moves)Card(child:ListTile(title:Text('${m.type.toUpperCase()} • ${m.quantity}'),subtitle:Text('Product ${m.productId}\n${m.date}'),isThreeLine:true)),],if(tab==4)...[for(final s in sales)Card(child:ListTile(title:Text('Invoice ${s.id.substring(s.id.length-6)}'),subtitle:Text('${s.date} • ${money(s.total)}'),trailing:FilledButton(onPressed:()=>receipt(s),child:const Text('View')))),],if(tab==0&&suppliers.isEmpty)const Center(child:Padding(padding:EdgeInsets.all(30),child:Text('No suppliers yet'))),if(tab==1&&payments.isEmpty)const Center(child:Padding(padding:EdgeInsets.all(30),child:Text('No payments yet'))),if(tab==2&&returns.isEmpty)const Center(child:Padding(padding:EdgeInsets.all(30),child:Text('No returns yet'))),if(tab==3&&moves.isEmpty)const Center(child:Padding(padding:EdgeInsets.all(30),child:Text('No stock movements yet')))]))]),floatingActionButton:tab==0?FloatingActionButton.extended(onPressed:()=>supplierDialog(),icon:const Icon(Icons.person_add),label:const Text('Supplier')):tab==1?FloatingActionButton.extended(onPressed:paymentDialog,icon:const Icon(Icons.payments),label:const Text('Payment')):tab==2?FloatingActionButton.extended(onPressed:returnDialog,icon:const Icon(Icons.assignment_return),label:const Text('Return')):tab==3?FloatingActionButton.extended(onPressed:stockMoveDialog,icon:const Icon(Icons.swap_vert),label:const Text('Stock move')):null);}
}
