import 'package:flutter/material.dart';
import '../models/business_models.dart';
import '../services/business_store.dart';

class FinanceScreen extends StatefulWidget { const FinanceScreen({super.key, required this.store}); final BusinessStore store; @override State<FinanceScreen> createState()=>_FinanceScreenState(); }
class _FinanceScreenState extends State<FinanceScreen> {
  int tab=0;
  void addExpense(){ final title=TextEditingController(), amount=TextEditingController(), note=TextEditingController(); _dialog('Add Expense',[title,amount,note],['Title','Amount','Note'],(){ final a=double.tryParse(amount.text); if(title.text.trim().isEmpty||a==null||a<=0)return; final list=widget.store.expenses; list.add(BusinessExpense(id:'${DateTime.now().microsecondsSinceEpoch}',date:DateTime.now(),title:title.text.trim(),amount:a,note:note.text)); widget.store.saveExpenses(list); setState((){}); }); }
  void addPurchase(){ final supplier=TextEditingController(), amount=TextEditingController(), paid=TextEditingController(), note=TextEditingController(); _dialog('Add Purchase',[supplier,amount,paid,note],['Supplier','Amount','Paid','Note'],(){ final a=double.tryParse(amount.text), p=double.tryParse(paid.text.isEmpty?'0':paid.text); if(supplier.text.trim().isEmpty||a==null||a<=0||p==null||p<0||p>a)return; final list=widget.store.purchases; list.add(Purchase(id:'${DateTime.now().microsecondsSinceEpoch}',date:DateTime.now(),supplier:supplier.text.trim(),amount:a,paid:p,note:note.text)); widget.store.savePurchases(list); setState((){}); }); }
  void _dialog(String title,List<TextEditingController> cs,List<String> labels,VoidCallback save){ showDialog(context:context,builder:(_)=>AlertDialog(title:Text(title),content:SingleChildScrollView(child:Column(children:[for(int i=0;i<cs.length;i++)Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:cs[i],keyboardType:i==0||labels[i]=='Note'||labels[i]=='Supplier'||labels[i]=='Title'?TextInputType.text:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:labels[i],border:const OutlineInputBorder())))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:(){save();Navigator.pop(context);},child:const Text('Save'))])); }
  @override Widget build(BuildContext context){ final expenses=widget.store.expenses.reversed.toList(), purchases=widget.store.purchases.reversed.toList(); return Column(children:[Padding(padding:const EdgeInsets.all(12),child:SegmentedButton<int>(segments:const [ButtonSegment(value:0,label:Text('Expenses'),icon:Icon(Icons.receipt_long)),ButtonSegment(value:1,label:Text('Purchases'),icon:Icon(Icons.shopping_cart))],selected:{tab},onSelectionChanged:(s)=>setState(()=>tab=s.first))),Expanded(child:tab==0?ListView(padding:const EdgeInsets.all(12),children:[_summary('Total expense',expenses.fold(0.0,(a,e)=>a+e.amount)),...expenses.map((e)=>Card(child:ListTile(leading:const Icon(Icons.money_off),title:Text(e.title),subtitle:Text(e.date.toString().split('.').first),trailing:Text('৳${e.amount.toStringAsFixed(2)}'))))]):ListView(padding:const EdgeInsets.all(12),children:[_summary('Purchase due',purchases.fold(0.0,(a,e)=>a+e.due)),...purchases.map((e)=>Card(child:ListTile(leading:const Icon(Icons.shopping_cart),title:Text(e.supplier),subtitle:Text('Paid ৳${e.paid.toStringAsFixed(2)} • Due ৳${e.due.toStringAsFixed(2)}'),trailing:Text('৳${e.amount.toStringAsFixed(2)}'))))])),floatingActionButton:FloatingActionButton.extended(onPressed:tab==0?addExpense:addPurchase,icon:const Icon(Icons.add),label:Text(tab==0?'Expense':'Purchase'))]); }
  Widget _summary(String t,double v)=>Card(child:Padding(padding:const EdgeInsets.all(18),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w600)),Text('৳${v.toStringAsFixed(2)}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))])));
}
