import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'services/business_store.dart';
import 'screens/products_screen.dart';
import 'screens/customers_screen.dart';
import 'screens/sales_screen.dart';

void main() async { WidgetsFlutterBinding.ensureInitialized(); final prefs = await SharedPreferences.getInstance(); runApp(Business360App(prefs: prefs)); }
class Business360App extends StatefulWidget { const Business360App({super.key, required this.prefs}); final SharedPreferences prefs; @override State<Business360App> createState()=>_Business360AppState(); }
class _Business360AppState extends State<Business360App>{ int index=0; late BusinessStore store; ThemeMode mode=ThemeMode.light; @override void initState(){super.initState();store=BusinessStore(widget.prefs);mode=widget.prefs.getBool('dark_mode')==true?ThemeMode.dark:ThemeMode.light;} void toggleTheme(){setState(()=>mode=mode==ThemeMode.light?ThemeMode.dark:ThemeMode.light);widget.prefs.setBool('dark_mode',mode==ThemeMode.dark);} @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Business360',themeMode:mode,theme:ThemeData(useMaterial3:true,colorSchemeSeed:const Color(0xFF6C57F5)),darkTheme:ThemeData(useMaterial3:true,colorSchemeSeed:const Color(0xFF8B7CFF),brightness:Brightness.dark),home:HomeScreen(index:index,onIndexChanged:(v)=>setState(()=>index=v),onTheme:toggleTheme,dark:mode==ThemeMode.dark,store:store)); }
class HomeScreen extends StatelessWidget{ const HomeScreen({super.key,required this.index,required this.onIndexChanged,required this.onTheme,required this.dark,required this.store}); final int index; final ValueChanged<int> onIndexChanged; final VoidCallback onTheme; final bool dark; final BusinessStore store; static const pages=['Dashboard','Sales / POS','Products & Stock','Customers','Reports']; Widget page(){switch(index){case 1:return SalesScreen(store:store);case 2:return ProductsScreen(store:store);case 3:return CustomersScreen(store:store);default:return index==0?DashboardPage(store:store):const ModulePage(title:'Reports');}} @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Business360'),actions:[IconButton(onPressed:onTheme,icon:Icon(dark?Icons.light_mode:Icons.dark_mode))]),drawer:Drawer(child:SafeArea(child:ListView(padding:const EdgeInsets.all(12),children:[const Padding(padding:EdgeInsets.all(16),child:Text('Business360',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold))),for(var i=0;i<pages.length;i++)ListTile(leading:Icon([Icons.dashboard,Icons.point_of_sale,Icons.inventory_2,Icons.people,Icons.bar_chart][i]),title:Text(pages[i]),selected:index==i,onTap:(){Navigator.pop(context);onIndexChanged(i);})]))),body:SafeArea(child:page()),bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:onIndexChanged,destinations:const[NavigationDestination(icon:Icon(Icons.dashboard_outlined),selectedIcon:Icon(Icons.dashboard),label:'Dashboard'),NavigationDestination(icon:Icon(Icons.point_of_sale_outlined),selectedIcon:Icon(Icons.point_of_sale),label:'Sales'),NavigationDestination(icon:Icon(Icons.inventory_2_outlined),selectedIcon:Icon(Icons.inventory_2),label:'Stock'),NavigationDestination(icon:Icon(Icons.people_outline),selectedIcon:Icon(Icons.people),label:'Customers'),NavigationDestination(icon:Icon(Icons.bar_chart_outlined),selectedIcon:Icon(Icons.bar_chart),label:'Reports')])); }
class ModulePage extends StatelessWidget{const ModulePage({super.key,required this.title});final String title;@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[Text(title,style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:16),Card(child:Padding(padding:const EdgeInsets.all(20),child:Text('$title module is being migrated.')))]);}
class DashboardPage extends StatelessWidget{const DashboardPage({super.key,required this.store});final BusinessStore store;@override Widget build(BuildContext context){final products=store.products,customers=store.customers,sales=store.sales;final totalSales=sales.fold<double>(0,(a,s)=>a+s.total),due=customers.fold<double>(0,(a,c)=>a+c.due),stockValue=products.fold<double>(0,(a,p)=>a+p.cost*p.stock);final cards=[('Sales','৳${totalSales.toStringAsFixed(2)}',Icons.point_of_sale),('Products','${products.length}',Icons.inventory_2),('Customers','${customers.length}',Icons.people),('Due','৳${due.toStringAsFixed(2)}',Icons.account_balance_wallet),('Stock value','৳${stockValue.toStringAsFixed(2)}',Icons.warehouse)];return ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:const[Text('Business360',style:TextStyle(fontSize:26,fontWeight:FontWeight.bold)),SizedBox(height:6),Text('Smart Business Management')]))),const SizedBox(height:12),GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:cards.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.25),itemBuilder:(_,i)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Icon(cards[i].$3,size:30),const SizedBox(height:10),Text(cards[i].$1),const SizedBox(height:4),Text(cards[i].$2,style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))]))))]);}}
