import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'services/business_store.dart';
import 'screens/customers_screen.dart';
import 'screens/finance_screen.dart';
import 'screens/products_screen.dart';
import 'screens/reports_screen.dart';
import 'screens/sales_screen.dart';
import 'screens/settings_screen.dart';

Future<void> main() async { WidgetsFlutterBinding.ensureInitialized(); final prefs=await SharedPreferences.getInstance(); runApp(Business360App(prefs:prefs)); }

class Business360App extends StatefulWidget { const Business360App({super.key,required this.prefs}); final SharedPreferences prefs; @override State<Business360App> createState()=>_Business360AppState(); }
class _Business360AppState extends State<Business360App>{ late final BusinessStore store; int index=0; ThemeMode mode=ThemeMode.light; String appBg='blueWhite',theme='purple';
 @override void initState(){super.initState();store=BusinessStore(widget.prefs);_load();}
 void _load(){mode=widget.prefs.getBool('dark_mode')==true?ThemeMode.dark:ThemeMode.light;appBg=widget.prefs.getString('appBg')??'blueWhite';theme=widget.prefs.getString('theme')??'purple';}
 void refresh(){setState(_load);}
 void toggleTheme(){setState(()=>mode=mode==ThemeMode.light?ThemeMode.dark:ThemeMode.light);widget.prefs.setBool('dark_mode',mode==ThemeMode.dark);}
 Color bg(){switch(appBg){case'midnight':return const Color(0xFF101522);case'slate':return const Color(0xFF202735);case'cream':return const Color(0xFFFFF8EA);default:return const Color(0xFFF4F7FC);}}
 Color seed(){switch(theme){case'blue':return const Color(0xFF087EA4);case'green':return const Color(0xFF15803D);case'dark':return const Color(0xFF7C83FD);default:return const Color(0xFF6C57F5);}}
 @override Widget build(BuildContext context){final light=ThemeData(useMaterial3:true,colorSchemeSeed:seed(),scaffoldBackgroundColor:bg());final dark=ThemeData(useMaterial3:true,colorSchemeSeed:seed(),brightness:Brightness.dark,scaffoldBackgroundColor:bg());return MaterialApp(debugShowCheckedModeBanner:false,title:'Business360',theme:light,darkTheme:dark,themeMode:mode,home:HomeScreen(index:index,onIndexChanged:(v)=>setState(()=>index=v),onTheme:toggleTheme,dark:mode==ThemeMode.dark,store:store,prefs:widget.prefs,onSettingsChanged:refresh));}}

class HomeScreen extends StatelessWidget{const HomeScreen({super.key,required this.index,required this.onIndexChanged,required this.onTheme,required this.dark,required this.store,required this.prefs,required this.onSettingsChanged});final int index;final ValueChanged<int> onIndexChanged;final VoidCallback onTheme,onSettingsChanged;final bool dark;final BusinessStore store;final SharedPreferences prefs;
 static const pages=['Dashboard','Sales / POS','Products & Stock','Customers','Reports','Purchases & Expenses'];
 Widget page(){switch(index){case 1:return SalesScreen(store:store);case 2:return ProductsScreen(store:store);case 3:return CustomersScreen(store:store);case 4:return ReportsScreen(store:store);case 5:return FinanceScreen(store:store);default:return DashboardPage(store:store,prefs:prefs);}}
 @override Widget build(BuildContext context){const icons=[Icons.dashboard,Icons.point_of_sale,Icons.inventory_2,Icons.people,Icons.bar_chart,Icons.account_balance_wallet];return Scaffold(appBar:AppBar(title:Text(index<pages.length?pages[index]:'Dashboard'),actions:[IconButton(onPressed:onTheme,icon:Icon(dark?Icons.light_mode:Icons.dark_mode)),IconButton(onPressed:()=>showModalBottomSheet(context:context,isScrollControlled:true,builder:(_)=>SizedBox(height:MediaQuery.sizeOf(context).height*.9,child:SettingsScreen(prefs:prefs,store:store,onChanged:onSettingsChanged))),icon:const Icon(Icons.settings))]),drawer:Drawer(child:SafeArea(child:ListView(padding:const EdgeInsets.all(12),children:[const Padding(padding:EdgeInsets.all(16),child:Text('Business360',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold))),for(var i=0;i<pages.length;i++)ListTile(leading:Icon(icons[i]),title:Text(pages[i]),selected:index==i,onTap:(){Navigator.pop(context);onIndexChanged(i);}),ListTile(leading:const Icon(Icons.settings),title:const Text('Settings'),onTap:(){Navigator.pop(context);showModalBottomSheet(context:context,isScrollControlled:true,builder:(_)=>SizedBox(height:MediaQuery.sizeOf(context).height*.9,child:SettingsScreen(prefs:prefs,store:store,onChanged:onSettingsChanged)));})])),body:SafeArea(child:page()),bottomNavigationBar:NavigationBar(selectedIndex:index>4?0:index,onDestinationSelected:onIndexChanged,destinations:const[NavigationDestination(icon:Icon(Icons.dashboard_outlined),selectedIcon:Icon(Icons.dashboard),label:'Home'),NavigationDestination(icon:Icon(Icons.point_of_sale_outlined),selectedIcon:Icon(Icons.point_of_sale),label:'Sales'),NavigationDestination(icon:Icon(Icons.inventory_2_outlined),selectedIcon:Icon(Icons.inventory_2),label:'Stock'),NavigationDestination(icon:Icon(Icons.people_outline),selectedIcon:Icon(Icons.people),label:'Customers'),NavigationDestination(icon:Icon(Icons.bar_chart_outlined),selectedIcon:Icon(Icons.bar_chart),label:'Reports') ]));}}

class DashboardPage extends StatelessWidget{const DashboardPage({super.key,required this.store,required this.prefs});final BusinessStore store;final SharedPreferences prefs;
 @override Widget build(BuildContext context){final products=store.products,customers=store.customers,sales=store.sales;final currency=prefs.getString('currency')??'৳';final totalSales=sales.fold<double>(0,(s,x)=>s+x.total);final profit=sales.fold<double>(0,(s,x)=>s+x.profit);final due=customers.fold<double>(0,(s,x)=>s+x.due);final stock=products.fold<double>(0,(s,x)=>s+x.cost*x.stock);final expenses=store.expenses.fold<double>(0,(s,x)=>s+x.amount);final purchases=store.purchases.fold<double>(0,(s,x)=>s+x.amount);final cards=[('Sales','$currency${totalSales.toStringAsFixed(2)}',Icons.point_of_sale),('Profit','$currency${profit.toStringAsFixed(2)}',Icons.trending_up),('Products','${products.length}',Icons.inventory_2),('Customers','${customers.length}',Icons.people),('Due','$currency${due.toStringAsFixed(2)}',Icons.account_balance_wallet),('Stock value','$currency${stock.toStringAsFixed(2)}',Icons.warehouse),('Expenses','$currency${expenses.toStringAsFixed(2)}',Icons.money_off),('Purchases','$currency${purchases.toStringAsFixed(2)}',Icons.shopping_cart)];return ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(prefs.getString('shop')??'আমার দোকান',style:const TextStyle(fontSize:26,fontWeight:FontWeight.bold)),const SizedBox(height:6),Text(prefs.getString('address')??'Smart Business Management'),if((prefs.getString('phone')??'').isNotEmpty)Text(prefs.getString('phone')!)]))),const SizedBox(height:12),GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:cards.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.2),itemBuilder:(context,i){final c=cards[i];return Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Icon(c.$3,size:30),const SizedBox(height:10),Text(c.$1),const SizedBox(height:4),Text(c.$2,style:const TextStyle(fontSize:19,fontWeight:FontWeight.bold))])));})]);}}
